"""Initial migration.

Revision ID: 1a7614da432d
Revises: 
Create Date: 2025-09-04 08:44:24.191691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7614da432d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('Roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Roles_default'), ['default'], unique=False)

    op.create_table('RouteTemplates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('RouteStages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['Stages.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['RouteTemplates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_username'), ['username'], unique=True)

    op.create_table('AuditLogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), server_default='general', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('AuditLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_AuditLogs_timestamp'), ['timestamp'], unique=False)

    op.create_table('Parts',
    sa.Column('part_id', sa.String(), nullable=False),
    sa.Column('product_designation', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('material', sa.String(length=150), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('quantity_total', sa.Integer(), server_default='1', nullable=False),
    sa.Column('quantity_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('drawing_filename', sa.String(length=255), nullable=True),
    sa.Column('route_template_id', sa.Integer(), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['Parts.part_id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['route_template_id'], ['RouteTemplates.id'], ),
    sa.PrimaryKeyConstraint('part_id')
    )
    with op.batch_alter_table('Parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Parts_parent_id'), ['parent_id'], unique=False)

    op.create_table('PartNotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['Parts.part_id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['Stages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('PartNotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PartNotes_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_PartNotes_timestamp'), ['timestamp'], unique=False)

    op.create_table('ResponsibleHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['Parts.part_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ResponsibleHistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ResponsibleHistory_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ResponsibleHistory_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_ResponsibleHistory_user_id'), ['user_id'], unique=False)

    op.create_table('StatusHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['Parts.part_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('StatusHistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_StatusHistory_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('StatusHistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_StatusHistory_timestamp'))

    op.drop_table('StatusHistory')
    with op.batch_alter_table('ResponsibleHistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ResponsibleHistory_user_id'))
        batch_op.drop_index(batch_op.f('ix_ResponsibleHistory_timestamp'))
        batch_op.drop_index(batch_op.f('ix_ResponsibleHistory_part_id'))

    op.drop_table('ResponsibleHistory')
    with op.batch_alter_table('PartNotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PartNotes_timestamp'))
        batch_op.drop_index(batch_op.f('ix_PartNotes_part_id'))

    op.drop_table('PartNotes')
    with op.batch_alter_table('Parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Parts_parent_id'))

    op.drop_table('Parts')
    with op.batch_alter_table('AuditLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AuditLogs_timestamp'))

    op.drop_table('AuditLogs')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_username'))

    op.drop_table('Users')
    op.drop_table('RouteStages')
    op.drop_table('Stages')
    op.drop_table('RouteTemplates')
    with op.batch_alter_table('Roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Roles_default'))

    op.drop_table('Roles')
    # ### end Alembic commands ###
